### ISSUE TITLE
models.py

### ISSUE THREAD

**Issue by jilner** [ajithvallabai/CAAE-Age_Progression_Regression_Pytorch#1]
Hello,when I run main.py, there is a problem in models.py,
line 180
    def __init__(self):
    ^
IndentationError: expected an indented block

what should I do?  thanks very much

**Comment by ajithvcoder** [comment]
hi @jilner  the project is not finished need to start the project again.

**Comment by ajithvcoder** [comment]
@jilner  i have fixed the issue
