### ISSUE TITLE
where is Encoder()

### ISSUE THREAD

**Issue by jilner** [ajithvallabai/CAAE-Age_Progression_Regression_Pytorch#2]
hello    there is no Encoder() and other functions,  where can i find them

**Comment by ajithvcoder** [comment]
hi @jilner the project is not finished need to start the project again. if possible we both can complete it

**Comment by jilner** [comment]
> hi @jilner the project is not finished need to start the project again. if possible we both can complete it

I'm happy to do this, but  i'm a newer ,so I hope I can ask you for advice when I encounter problems

**Comment by ajithvcoder** [comment]
ok

**Comment by liyuanyaun** [comment]
do you both complete this job now? @jilner @ajithvallabai   now i encounter a problem "name 'Encoder' is not defined"

**Comment by NITROGENousFish** [comment]
it seem that Encoder still not complete yet. Btw in Google drive only part1 of the croped data, what about the others~~

**Comment by NITROGENousFish** [comment]
It seems class Encoder still not complete yet. Btw in Google drive only part1 of the croped data, what about the others~~

**Comment by ajithvcoder** [comment]
@liyuanyaun i have updated the repo @NITROGENousFish  UTK dataset you can find in google i took from one repo
