### ISSUE TITLE
fixed_noise.p problem

### ISSUE THREAD

**Issue by HuangYin0514** [ajithvallabai/CAAE-Age_Progression_Regression_Pytorch#3]
where is the file of fixed_noise.p ?

            pickle.dump(fixed_noise,open("fixed_noise.p","wb"))

**Comment by liyuanyaun** [comment]
how do you solve the problem of no definition of "Encoder"  @HuangYin0514 @ajithvallabai

**Comment by shivanikush** [comment]
the definition of Encoder is  written inside CAAE_128_jupyter.ipynb you can create a .py file from that Encoder's definition is solved. But "fixed_noise.p" is unknown that what it contains.. @ajithvallabai  explain about "fixed_noise.p", how to create it and what it contains

**Comment by PallaviMadhukar** [comment]
How to create the fixed_noise.p file and what is it?

**Comment by ajithvcoder** [comment]
@shivanikush @PallaviMadhukar  please find the main.py file for proper execution , creating the fixed_noise.p is explained in it
