### ISSUE TITLE
about class UpsampleConvLayer 

### ISSUE THREAD

**Issue by NITROGENousFish** [ajithvallabai/CAAE-Age_Progression_Regression_Pytorch#4]
Hello~, In the official paper (CVPR2018 version or TPAMI version) 3.2 Generator, the say **"Rather than using the max-pooling and upsampling layers to calculate the feature maps, we employ the 3× 3 convolution kernels with a stride of 2, ensuring that every pixel contributes and the adjacent pixels transform in a synergistic manner. "**

I just wonder in your code **class UpsampleConvLayer** , is that right to add this layer to **class ImageTransformNet** ?? , thanks~

**Comment by ajithvcoder** [comment]
@NITROGENousFish  will fix the issue soon
