### ISSUE TITLE
complete

### ISSUE THREAD

**Issue by whf9527** [ajithvallabai/CAAE-Age_Progression_Regression_Pytorch#5]
hi，this is complete project ？？？

**Comment by ajithvcoder** [comment]
@whf9527   its incomplete . Will complete it in few months

**Comment by ajithvcoder** [comment]
@whf9527 if you are free we can collaborate to complete this work ?

**Comment by whf9527** [comment]
it is the topic of my graducation project.&nbsp; but the tutor advised me to change the subject.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ajith"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 晚上7:43
收件人:&nbsp;"ajithvallabai/Pyramid-Architecture-of-GANs"<Pyramid-Architecture-of-GANs@noreply.github.com&gt;;
抄送:&nbsp;"夜星"<1870018064@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ajithvallabai/Pyramid-Architecture-of-GANs] complete (#5)




@whf9527   its incomplete . Will complete it in few months

**Comment by ajithvcoder** [comment]
@whf9527  great . so if you change the subject you will be working on this or not ?

**Comment by ajithvcoder** [comment]
@whf9527  its complete please find the colab notebook for execution instructions or readme
